version: '3.3'
services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'eazybank'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

volumes:
  mysql_data:
