services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "eazybank"
      MYSQL_USER: "eazybank"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
  keycloak:
    container_name: keycloak
    ports:
      - "8180:8080"
    image: "quay.io/keycloak/keycloak:26.0.7"
    command: "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data/

volumes:
  keycloak-data:
  mysql_data:
