spring:
  application:
    name: eazyschool
logging:
  level:
    '[org.springframework.security]': ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  # Use this pattern to display the log in a readable format
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}